version: 2.1

jobs:
  build:
    macos:
      xcode: "16.4.0"

    resource_class: m4pro.large

    environment:
      DEPOT_TOOLS_UPDATE: "0"
      GCLIENT_PY3: "1"
      THOR_DIR: "$HOME/project"

    steps:
      - checkout

      - run:
          name: Install depot_tools & Fetch Chromium source
          command: |
            cd $HOME/project/

            python3 $HOME/project/get_repo.py --thorium-root $HOME/project --no-history --yes
            echo 'export PATH="$HOME/depot_tools:$PATH"' >> $BASH_ENV
            
      - run:
          name: Prepare Thorium patches
          command: |
            source $BASH_ENV

            cd $HOME/project

            python3 $HOME/project/version.py --thorium-root $HOME/project

            python3 $HOME/project/setup.py --mac --thorium-root $HOME/project


      - run:
          name: Configure GN ARM64 build
          command: |
            source $BASH_ENV

            cd $HOME/chromium/src

            mkdir -p out/thorium

            cp $HOME/project/other/Mac/mac_ARM_args.gn \
              out/thorium/args.gn

            gn gen out/thorium


      - run:
          name: Build Thorium ARM64
          command: |
            source $BASH_ENV

            cd $HOME/project
            python3 $HOME/project/build.py --thorium-root $HOME/project


      - run:
          name: Create DMG
          command: |
            source $BASH_ENV

            cd $HOME/project

            python3 $HOME/project/create_dmg.py


      - store_artifacts:
          path: $HOME/chromium/src/out/thorium/Thorium_MacOS.dmg
          destination: Thorium.dmg


workflows:
  build:
    jobs:
      - build
